version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8085:80"
    networks:
      - internal
    volumes:
      - ./docs/:/var/www/html/docs
      - ./docker/logs:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/src
      - ./docs/:/var/www/html/docs
      - ./tests/:/var/www/html/tests
      - ./vendor/:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge