version: "3"
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/src
      - ./tests/:/var/www/html/tests
      - ./vendor/:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./docker/logs/php.log:/var/log/fpm-php.www.log